name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: choice
        options:
          - production
          - staging
      VERSION_TAG:
        description: 'Specify the version tag for deployment'
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: string
      VERSION_TAG:
        description: 'Specify the version tag for deployment'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    env:
      VERSION_TAG: ${{ inputs.VERSION_TAG }}
      TERRATEAM_ENVIRONMENT: ${{ inputs.environment }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      MATRIX_PASSWORD: ${{ secrets.MATRIX_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Fly.io authentication
        run: ./scripts/auth_flyio

      - name: Deploy to Fly.io
        run: ./scripts/deploy_flyio

      - name: Notify Matrix
        run: ./scripts/notify_matrix
